### ISSUE TITLE
Examples dont work

### ISSUE THREAD

**Issue by Narven** [dixonwille/wmenu#7]
What is Opt in `actFunc := func(opt Opt) error {`

?

thanks

**Comment by dixonwille** [comment]
Hey sorry about that. Try

```go
actFunc := func(opt wmenu.Opt) error {}
```

This is what `menu.Action()` needs as a parameter. Basically, the next function to call if an option does not have an action set to it. In this case `opt` will be the option that was selected in the menu. This allows you to have a context passed through to the next function. Will fix readme shortly. Let me now if that helps. If not let me now of anything else I can do to clarify.
