### ISSUE TITLE
Convenient Action Handler

### ISSUE THREAD

**Issue by NicolasSiver** [dixonwille/wmenu#8]
Looks like if you are working with a list where It's possible to have multiple selections, you have to provide both handlers - `Action` and `MultipleAction`. I had to spend some time to comprehend it.

Why not just create an action handler, where if a single option is selected it will be a slice with one element only?

**Comment by dixonwille** [comment]
@NicolasSiver 
I think there was a reason or a poor design plan on my part. Not sure which since this was one of my first GoLang projects. I have since done better with internal tools for work. I'll look at it when I get time.

**Comment by dixonwille** [comment]
@NicolasSiver Looking into this and it seems it was just poor design. It will take some time for me to fix. Things Todo:

- [ ] Remove MultiFunc
- [ ] Add Multi-answer boolean
- [ ] Change defaultFunc to work with slices of options
- [ ] Make sure nothing else broke
- [ ] Release Version 3 as this is a breaking change

I'll try to keep this comment up to date with my progress

**Comment by dixonwille** [comment]
Ran through UTs, Report Card, and GoDocs and couldn't find anything I missed.

I:

* Removed `MultipleAction()`
* Edited `Action()` to accept a slice of `Options`
* Added `AllowMultiple()` to still allow for that check
* Fixed UTs
* Checked Code Coverage
* Checked Code Quality (Go Report Card)
* Made a V3 branch to keep up with that
* Master is now on V4 (tags)
* Updated the Readme

Hope this helps! @NicolasSiver
