### ISSUE TITLE
Trailing delimiter

### ISSUE THREAD

**Issue by NicolasSiver** [dixonwille/wmenu#9]
Looks like a trailing delimiter considered as an invalid response.
For example, if `space` is a delimiter, such response will not be accepted:

```
0_1_
// where underscore _ is a space for clarity
```

**Comment by dixonwille** [comment]
Will actually need to look into a different package to trim before split. Thanks

**Comment by dixonwille** [comment]
https://github.com/dixonwille/wlog I would like to reference this package as well that I am using for getting answers and printing to string. I may open an issue there to add an enhancement to that package to be able to trim the response by certain characters (spaces, `,`, or whatever delimiter you use).
